# Generated by Django 4.0.4 on 2022-06-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_instagrampost_editor_instagrampost_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
