# Generated by Django 4.0.4 on 2022-06-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_instagrampost_options_alter_instagrampost_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
